// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace appId with the exact Web app ID from Firebase Console after you
  // register the web app. It looks like: 1:652471613625:web:xxxxxxxxxxxxxxxx.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTKZmJ6K-0_GjnUsgCeKUygxiTz4DuZCU',
    appId: '1:652471613625:web:cfb7c1cf1df60cbec58368',
    messagingSenderId: '652471613625',
    projectId: 'mushroom-database-16462',
    authDomain: 'mushroom-database-16462.firebaseapp.com',
    databaseURL:
        'https://mushroom-database-16462-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mushroom-database-16462.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTKZmJ6K-0_GjnUsgCeKUygxiTz4DuZCU',
    appId: '1:652471613625:android:65267ec67a883397c58368',
    messagingSenderId: '652471613625',
    projectId: 'mushroom-database-16462',
    databaseURL:
        'https://mushroom-database-16462-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mushroom-database-16462.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcdB4D35kUlPOLZWQ3yyO_Lsql8Ybam2c',
    appId: '1:652471613625:ios:eb8b77343cbbbf92c58368',
    messagingSenderId: '652471613625',
    projectId: 'mushroom-database-16462',
    databaseURL:
        'https://mushroom-database-16462-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mushroom-database-16462.firebasestorage.app',
    iosBundleId: 'com.example.smartGrowCode',
  );
}
